AWSTemplateFormatVersion: '2010-09-09'
Description: 'My Things Management - Solutions - Version %%VERSION%%'

Parameters:
    sourceS3Bucket:
        Type: String
        Description: My Things Management S3 bucket.
    sourceKeyPrefix:
        Type: String
        Description: My Things management Source key prefix.
    greengrassSourceKeyPrefix:
        Type: String
        Description: My Things management source key prefix for the greengrass lambda function code
    deviceBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the device blueprints
    deviceTypesTable:
        Type: String
        Description: DynamoDB Table for storing the device types
    solutionBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the solution blueprints
    customResourceUtilsHelperArn:
        Type: String
        Description: Utils custom resource helper ARN
    deploymentUUID:
        Type: String
        Description: Used to force update / create of inits
    dataS3Bucket:
        Type: String
        Description: My Things Management Data S3 Bucket
    dataS3BucketArn:
        Type: String
        Description: My Things Management Data S3 Bucket ARN
    solutionsGreengrassGroupRole:
        Type: String
        Description: My Things Management Greengrass Group Role


Mappings:
    Solutions:
        Solution:
            AMCF1: 'aws-mini-connected-factory-v1.0'

Resources:

    # Nested stack - Custom resource - S3 Helper
    CFStackForSolutionsAMCF1:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref sourceS3Bucket, !Ref sourceKeyPrefix, !FindInMap ['Solutions', 'Solution', 'AMCF1'], !Join ['.', [!FindInMap ['Solutions', 'Solution', 'AMCF1'], 'yml']]]]
            Parameters:
                sourceS3Bucket: !Ref sourceS3Bucket
                sourceKeyPrefix: !Join ['/', [!Ref sourceKeyPrefix, !FindInMap ['Solutions', 'Solution', 'AMCF1']]]
                greengrassSourceKeyPrefix: !Ref greengrassSourceKeyPrefix
                deviceBlueprintsTable: !Ref deviceBlueprintsTable
                deviceTypesTable: !Ref deviceTypesTable
                solutionBlueprintsTable: !Ref solutionBlueprintsTable
                customResourceUtilsHelperArn: !Ref customResourceUtilsHelperArn
                deploymentUUID: !Ref deploymentUUID
                dataS3Bucket: !Ref dataS3Bucket
                dataS3BucketArn: !Ref dataS3BucketArn
                solutionsGreengrassGroupRole: !Ref solutionsGreengrassGroupRole
