AWSTemplateFormatVersion: '2010-09-09'
Description: 'My Things Management - CF Custom Resource Helper S3 Lambda - Version %%VERSION%%'
Parameters:
    sourceBucket:
        Type: String
        Description: S3 Bucket for Lambda code.
    sourceKeyPrefix:
        Type: String
        Description: S3 Bucket Key prefix for Lambda code.
    destBucketArn:
        Type: String
        Description: ARN of the My Things Management Website Bucket.
    dataBucketArn:
        Type: String
        Description: ARN of the My Things Management Data Bucket.
Resources:
    mtmCustomResourceS3HelperRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: 'Allow'
                      Principal:
                          Service:
                              - 'lambda.amazonaws.com'
                      Action:
                          - 'sts:AssumeRole'
            Path: '/'
            Policies:
                - PolicyName: 'mtmCustomResourceS3HelperPolicy'
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: 'Allow'
                            Action:
                                - 'logs:CreateLogGroup'
                                - 'logs:CreateLogStream'
                                - 'logs:PutLogEvents'
                            Resource: !Join ['', ['arn:aws:logs:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':log-group:/aws/lambda/mythings-mgmt-custom-resource-helper-s3:*']]
                          - Effect: 'Allow'
                            Action:
                                - 's3:GetObject'
                                - 's3:ListObjectsV2'
                            Resource:
                                - 'arn:aws:s3:::*'
                          - Effect: 'Allow'
                            Action:
                                - 's3:PutObject'
                            Resource:
                                - !Join ['/', [!Ref destBucketArn, '*']]
                                - !Join ['/', [!Ref dataBucketArn, '*']]

    mtmCustomResourceS3Helper:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'mythings-mgmt-custom-resource-helper-s3'
            Description: 'My Things Management Custom resource helper for deploying the app'
            Code:
                S3Bucket: !Ref sourceBucket
                S3Key: !Join ['/', [!Ref sourceKeyPrefix, 'mythings-mgmt-custom-resource-helper-s3.zip']]
            Handler: index.handler
            Runtime: nodejs8.10
            Role: !GetAtt mtmCustomResourceS3HelperRole.Arn
            Timeout: 300
            MemorySize: 256

Outputs:
    mtmCustomResourceS3HelperArn:
        Description: 'Custom Resource S3 Helper ARN'
        Value: !GetAtt mtmCustomResourceS3Helper.Arn
