AWSTemplateFormatVersion: '2010-09-09'
Description: 'My Things Management - Data Bucket - Version %%VERSION%%'

Resources:
    dataBucketAccessPolicy:
        Type: "AWS::IAM::ManagedPolicy"
        DeletionPolicy: Retain
        Properties:
            Description: "My Things Management policy to access the Data Bucket."
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: "Allow"
                        Action:
                            # TODO BE MORE RESTRICTIVE
                            - "s3:*"
                        Resource:
                            - !Join ["/", [!GetAtt dataBucket.Arn, "*"]]
    dataBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        Properties:
            CorsConfiguration:
                CorsRules:
                    -
                        AllowedOrigins:
                            - "*"
                        AllowedMethods:
                            - "HEAD"
                            - "GET"
                        AllowedHeaders:
                            - "*"
Outputs:
    # dataBucketAccessPolicy:
    #     Description: "IAM Policy to access the My Things Management Data bucket"
    #     Value: !GetAtt CFStackForDataBucket.Outputs.dataBucketAccessPolicy
    dataBucket:
        Description: 'My Things Management Data Bucket'
        Value: !Ref dataBucket
    dataBucketArn:
        Description: 'My Things Management Data Bucket ARN'
        Value: !GetAtt dataBucket.Arn
