AWSTemplateFormatVersion: '2010-09-09'
Description: 'My Things Management - DynamoDB Table - Solutions - Version %%VERSION%%'

Resources:

    solutionsTable:
        Type: "AWS::DynamoDB::Table"
        DeletionPolicy: "Delete"
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: "id"
                    AttributeType: "S"
                -
                    AttributeName: "thingId"
                    AttributeType: "S"
            KeySchema:
                -
                    AttributeName: "id"
                    KeyType: "HASH"
                -
                    AttributeName: "thingId"
                    KeyType: "RANGE"
            GlobalSecondaryIndexes:
                -
                    IndexName: 'deviceId'
                    KeySchema:
                        -
                            AttributeName: 'thingId'
                            KeyType: 'HASH'
                    Projection:
                        ProjectionType: 'ALL'
                    ProvisionedThroughput:
                        ReadCapacityUnits: 5
                        WriteCapacityUnits: 5
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
            SSESpecification:
                SSEEnabled: true
            TableName: "mythings-mgmt-solutions"


Outputs:
    solutionsTable:
        Description: "DynamoDB Solutions Table"
        Value: !Ref solutionsTable
