AWSTemplateFormatVersion: '2010-09-09'
Description: '(SO0053) - IoT Pilot Kickstart: Kickstart your IoT project, define, manage and monitor your IoT devices - (codename: sputnik) - Main - Version %%VERSION%%'
Parameters:
    AdministratorName:
        Type: String
        Description: Name of the sputnik administrator.
    AdministratorEmail:
        Type: String
        Description: Email address for sputnik administrator.
        AllowedPattern: "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"
    IsWebsitePublic:
        Type: String
        Description: Do you want to make the public S3 website public ?
        Default: false
        AllowedValues:
            - true
            - false

Mappings:
    Send:
        AnonymousUsage:
            Data: "Yes"
    SourceCode:
        App:
            ShortName: 'sputnik'
            FullName: 'sputnik - The Simple IoT Management System'
        General:
            S3Bucket: '%%BUCKET_NAME%%'
            KeyPrefix: 'sputnik/%%VERSION%%'

Resources:

    # ##########################################################################
    #
    # S3
    #
    # ##########################################################################
    # Nested stack - Data bucket creation
    CFStackForDataBucket:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'cf/sputnik-s3bucket-data.yml']]]]

    # Nested stack - Website bucket creation
    CFStackForWebsite:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'cf/sputnik-s3bucket-website.yml']]]]
            Parameters:
                IsWebsitePublic: !Ref IsWebsitePublic

    # ##########################################################################
    #
    # Cognito
    #
    # ##########################################################################
    # Nested stack - Cognito
    CFStackForCognito:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'cf/sputnik-cognito.yml']]]]
            Parameters:
                AdministratorName: !Ref AdministratorName
                AdministratorEmail: !Ref AdministratorEmail
                dataBucketArn: !GetAtt CFStackForDataBucket.Outputs.dataBucketArn
                websiteURL: !GetAtt CFStackForWebsite.Outputs.websiteUrl
                fullName: !FindInMap ['SourceCode', 'App', 'FullName']


    # ##########################################################################
    #
    # Dynamo DB
    #
    # ##########################################################################
    CFStackForDynamoDB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'cf/dynamodb/sputnik-ddb-tables.yml']]]]


    # ##########################################################################
    #
    # Lambda
    #
    # ##########################################################################
    CFStackForLambda:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'cf/lambda/sputnik-lambda.yml']]]]
            Parameters:
                sourceBucket: !Join ['-', [!FindInMap ['SourceCode', 'General', 'S3Bucket'], Ref: 'AWS::Region']]
                sourceKeyPrefix: !FindInMap ['SourceCode', 'General', 'KeyPrefix']
                destBucketArn: !GetAtt CFStackForWebsite.Outputs.websiteBucketArn
                dataBucket: !GetAtt CFStackForDataBucket.Outputs.dataBucket
                dataBucketArn: !GetAtt CFStackForDataBucket.Outputs.dataBucketArn
                settingsTable: !GetAtt CFStackForDynamoDB.Outputs.settingsTable
                devicesTable: !GetAtt CFStackForDynamoDB.Outputs.devicesTable
                deviceTypesTable: !GetAtt CFStackForDynamoDB.Outputs.deviceTypesTable
                deviceBlueprintsTable: !GetAtt CFStackForDynamoDB.Outputs.deviceBlueprintsTable
                deploymentsTable: !GetAtt CFStackForDynamoDB.Outputs.deploymentsTable
                systemsTable: !GetAtt CFStackForDynamoDB.Outputs.systemsTable
                systemBlueprintsTable: !GetAtt CFStackForDynamoDB.Outputs.systemBlueprintsTable
                greengrassServiceRoleArn: !GetAtt IAMGreengrassServiceRole.Arn
                iamRoleArnForGreengrassGroups: !GetAtt IAMRoleForGreengrassGroups.Arn
                iotPolicyForGreengrassCores: !Ref IoTPolicyForGreengrassCores
                iotConnectPolicyForSputnikCertificates: !Ref IoTConnectPolicyForSputnikCertificates
                userPoolId: !GetAtt CFStackForCognito.Outputs.userPoolId
                cfnStackId: !Ref AWS::StackId

    # ##########################################################################
    #
    # AppSync
    #
    # ##########################################################################
    CFStackForAppSync:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'cf/sputnik-appsync.yml']]]]
            Parameters:
                sourceBucket: !Join ['-', [!FindInMap ['SourceCode', 'General', 'S3Bucket'], Ref: 'AWS::Region']]
                sourceKeyPrefix: !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], !Join ['-', ['cf/graphql', '%%DEPLOYMENT_UUID%%']] ]]
                userPoolId: !GetAtt CFStackForCognito.Outputs.userPoolId
                settingsTable: !GetAtt CFStackForDynamoDB.Outputs.settingsTable
                dataStoreTable: !GetAtt CFStackForDynamoDB.Outputs.dataStoreTable
                devicesTable: !GetAtt CFStackForDynamoDB.Outputs.devicesTable
                deviceTypesTable: !GetAtt CFStackForDynamoDB.Outputs.deviceTypesTable
                deviceBlueprintsTable: !GetAtt CFStackForDynamoDB.Outputs.deviceBlueprintsTable
                deploymentsTable: !GetAtt CFStackForDynamoDB.Outputs.deploymentsTable
                systemsTable: !GetAtt CFStackForDynamoDB.Outputs.systemsTable
                systemBlueprintsTable: !GetAtt CFStackForDynamoDB.Outputs.systemBlueprintsTable
                lambdaServiceAdminArn: !GetAtt CFStackForLambda.Outputs.lambdaServiceAdminArn
                lambdaServiceDevicesArn: !GetAtt CFStackForLambda.Outputs.lambdaServiceDevicesArn
                lambdaServiceSettingsArn: !GetAtt CFStackForLambda.Outputs.lambdaServiceSettingsArn
                lambdaServiceDeploymentsArn: !GetAtt CFStackForLambda.Outputs.lambdaServiceDeploymentsArn
                lambdaServiceSystemsArn: !GetAtt CFStackForLambda.Outputs.lambdaServiceSystemsArn
                lambdaServiceUtilsArn: !GetAtt CFStackForLambda.Outputs.customResourceUtilsHelperArn


    # ##########################################################################
    #
    # CloudTrail
    #
    # ##########################################################################
    CFStackForCloudTrail:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'cf/sputnik-cloudtrail.yml']]]]


    # Greengrass Service Role
    IAMGreengrassServiceRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: 'Allow'
                      Principal:
                          Service:
                              - 'greengrass.amazonaws.com'
                      Action:
                          - 'sts:AssumeRole'
            Path: '/'
            ManagedPolicyArns:
                - 'arn:aws:iam::aws:policy/service-role/AWSGreengrassResourceAccessRolePolicy'

    # Systems Greengrass group role
    # NOTE: This is placed here, because else it creates a circular dependency between the Lambda Stack and the Systems Stack.
    IAMRoleForGreengrassGroups:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: 'Allow'
                      Principal:
                          Service:
                              - 'greengrass.amazonaws.com'
                      Action:
                          - 'sts:AssumeRole'
            Path: '/'

    # Systems IoT Policy for Greengrass devices
    # NOTE: This is placed here, because else it creates a circular dependency between the Lambda Stack and the Systems Stack.
    IoTPolicyForGreengrassCores:
        Type: "AWS::IoT::Policy"
        DeletionPolicy: Retain
        Properties:
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: "Allow"
                        Action:
                            - "iot:*"
                            - "greengrass:*"
                        Resource:
                            - "*"

    IoTConnectPolicyForSputnikCertificates:
        Type: "AWS::IoT::Policy"
        Properties:
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: "Allow"
                        Action: "iot:Connect"
                        Resource:
                            - !Join [':', ['arn:aws:iot', Ref: 'AWS::Region', Ref: 'AWS::AccountId', 'client/${iot:Certificate.Subject.CommonName}']]
                            - !Join [':', ['arn:aws:iot', Ref: 'AWS::Region', Ref: 'AWS::AccountId', 'client/${iot:Certificate.Subject.CommonName}-*']]
                        Condition:
                            StringEquals:
                                iot:Certificate.Subject.Organization: "sputnik"


    # ##########################################################################
    #
    # Init
    #
    # ##########################################################################

    iotEndpoint:
        Type: 'Custom::Lambda'
        Properties:
            ServiceToken: !GetAtt CFStackForLambda.Outputs.customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            customAction: 'iotDescribeEndpoint'
            # endpointType: 'iot:Data'
            endpointType: 'iot:Data-ATS'

    greengrassAssociateServiceRoleToAccount:
        Type: 'Custom::Lambda'
        Properties:
            ServiceToken: !GetAtt CFStackForLambda.Outputs.customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            customAction: 'greengrassAssociateServiceRoleToAccount'

    # Initialization - Copy of website assets (html/js/css/assets)
    website:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !GetAtt CFStackForLambda.Outputs.customResourceS3HelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Join ['-', [!FindInMap ['SourceCode', 'General', 'S3Bucket'], Ref: 'AWS::Region']]
            sourceS3Key: !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'console']]
            destS3Bucket: !GetAtt CFStackForWebsite.Outputs.websiteBucket
            customAction: 'copyS3assets'
            deploymentUUID: '%%DEPLOYMENT_UUID%%'


    websiteConfig:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !GetAtt CFStackForLambda.Outputs.customResourceS3HelperArn
            Region: !Ref 'AWS::Region'
            destS3Bucket: !GetAtt CFStackForWebsite.Outputs.websiteBucket
            destS3Key: 'assets/appVariables.js'
            varName: 'appVariables'
            file:
                VERSION: '%%VERSION%%'
                USER_POOL_ID: !GetAtt CFStackForCognito.Outputs.userPoolId
                USER_POOL_CLIENT_ID: !GetAtt CFStackForCognito.Outputs.websiteCognitoClientId
                IDENTITY_POOL_ID: !GetAtt CFStackForCognito.Outputs.identityPool
                REGION: !Ref 'AWS::Region'
                IOT_COGNITO_POLICY: !GetAtt CFStackForCognito.Outputs.websiteCognitoIoTPolicy
                S3_DATA_BUCKET: !GetAtt CFStackForDataBucket.Outputs.dataBucket
                APP_SYNC_GRAPHQL_ENDPOINT: !GetAtt CFStackForAppSync.Outputs.appSyncGraphQLUrl
                IOT_ENDPOINT: !GetAtt iotEndpoint.endpointAddress
                DEPLOYMENT_UUID: '%%DEPLOYMENT_UUID%%'
                ADDON_TEMPLATES_URL: !Join ['&', [
                    !Join ['=', ['param_addonSourceBucket', !Join ['-', [!FindInMap ['SourceCode', 'General', 'S3Bucket'], Ref: 'AWS::Region']]]],
                    !Join ['=', ['param_addonSourceKeyPrefix', !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'addons']]]],
                    !Join ['=', ['param_lambdaServiceDevicesArn', !GetAtt CFStackForLambda.Outputs.lambdaServiceDevicesArn]],
                    !Join ['=', ['param_dataStoreTable', !GetAtt CFStackForDynamoDB.Outputs.dataStoreTable]],
                    !Join ['=', ['param_deviceBlueprintsTable', !GetAtt CFStackForDynamoDB.Outputs.deviceBlueprintsTable]],
                    !Join ['=', ['param_deviceTypesTable', !GetAtt CFStackForDynamoDB.Outputs.deviceTypesTable]],
                    !Join ['=', ['param_settingsTable', !GetAtt CFStackForDynamoDB.Outputs.settingsTable]],
                    !Join ['=', ['param_systemBlueprintsTable', !GetAtt CFStackForDynamoDB.Outputs.systemBlueprintsTable]],
                    !Join ['=', ['param_customResourceUtilsHelperArn', !GetAtt CFStackForLambda.Outputs.customResourceUtilsHelperArn]],
                    !Join ['=', ['param_iamRoleForGreengrassGroups', !Ref IAMRoleForGreengrassGroups]],
                    !Join ['=', ['param_dataS3Bucket', !GetAtt CFStackForDataBucket.Outputs.dataBucket]],
                    !Join ['=', ['param_dataS3BucketArn', !GetAtt CFStackForDataBucket.Outputs.dataBucketArn]],
                    !Join ['=', ['templateURL', !Join ['/', ['https:/', !Join ['.', [!Join ['-', [!FindInMap ['SourceCode', 'General', 'S3Bucket'], Ref: 'AWS::Region']], 's3.amazonaws.com']], !FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'addons']]]],
                ]]
            customAction: 'putFile'
            deploymentUUID: '%%DEPLOYMENT_UUID%%'


    # Initialization - Init Settings
    initSettings:
        Type: 'Custom::LoadLambda'
        DependsOn: initAppUUID
        Properties:
            ServiceToken: !GetAtt CFStackForLambda.Outputs.customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            ddbTable: !GetAtt CFStackForDynamoDB.Outputs.settingsTable
            ddbItem:
                id: "app-config"
                type: "config"
                setting:
                    uuid: !GetAtt initAppUUID.UUID
                    mapboxToken: "NA"
                    anonymousData: !FindInMap ["Send", "AnonymousUsage", "Data"]
            customAction: 'dynamodbSaveItem'

    initAddonsSettings:
        Type: 'Custom::LoadLambda'
        DependsOn: initAppUUID
        Properties:
            ServiceToken: !GetAtt CFStackForLambda.Outputs.customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            ddbTable: !GetAtt CFStackForDynamoDB.Outputs.settingsTable
            ddbItem:
                id: "app-addons"
                type: "config"
                setting:
                    installed: []
            customAction: 'dynamodbSaveItem'

    # Initialization - UUID
    initAppUUID:
        Type: "Custom::LoadLambda"
        Properties:
            ServiceToken: !GetAtt CFStackForLambda.Outputs.customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            customAction: "createUUID"

    initAnonymousMetric:
        Type: "Custom::LoadLambda"
        Properties:
            ServiceToken: !GetAtt CFStackForLambda.Outputs.customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            UUID: !GetAtt initAppUUID.UUID
            version: '%%VERSION%%'
            anonymousData: !FindInMap ["Send", "AnonymousUsage", "Data"]
            customAction: "sendMetric"

    # ##########################################################################
    #
    # Defaults
    #
    # ##########################################################################
    CFStackForDefaults:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Join ['/', [!FindInMap ['SourceCode', 'General', 'KeyPrefix'], 'cf/defaults/sputnik-defaults.yml']]]]
            Parameters:
                sourceS3Bucket: !Join ['-', [!FindInMap ['SourceCode', 'General', 'S3Bucket'], Ref: 'AWS::Region']]
                sourceS3KeyPrefix: !FindInMap ['SourceCode', 'General', 'KeyPrefix']
                deviceTypesTable: !GetAtt CFStackForDynamoDB.Outputs.deviceTypesTable
                deviceBlueprintsTable: !GetAtt CFStackForDynamoDB.Outputs.deviceBlueprintsTable
                customResourceUtilsHelperArn: !GetAtt CFStackForLambda.Outputs.customResourceUtilsHelperArn
                deploymentUUID: '%%DEPLOYMENT_UUID%%'

Outputs:
    # UUID
    AppUUID:
        Description: "App UUID"
        Value: !GetAtt initAppUUID.UUID
    # Website
    websiteUrl:
        Description: 'sputnik Website URL'
        Value: !GetAtt CFStackForWebsite.Outputs.websiteUrl
    # Cognito
    userPoolArn:
        Description: "sputnik User Pool"
        Value: !GetAtt CFStackForCognito.Outputs.userPoolArn
    userPoolId:
        Description: "sputnik User Pool ID"
        Value: !GetAtt CFStackForCognito.Outputs.userPoolId
    websiteCognitoClientId:
        Description: "sputnik Website Cognito Client"
        Value: !GetAtt CFStackForCognito.Outputs.websiteCognitoClientId
    identityPool:
        Description: "sputnik Identity Pool"
        Value: !GetAtt CFStackForCognito.Outputs.identityPool
    websiteCognitoIoTPolicy:
        Description: "IoT Policy to access resources"
        Value: !GetAtt CFStackForCognito.Outputs.websiteCognitoIoTPolicy
    # IOT
    iotEndpoint:
        Description: "IoT Endpoint"
        Value: !GetAtt iotEndpoint.endpointAddress
    iamRoleForGreengrassGroups:
        Description: "IAM Role For Greengrass Groups to be used by Addons"
        Value: !Ref IAMRoleForGreengrassGroups
    # dataBucketAccessPolicy:
    #     Description: "IAM Policy to access the sputnik Data bucket"
    #     Value: !GetAtt CFStackForDataBucket.Outputs.dataBucketAccessPolicy

