AWSTemplateFormatVersion: '2010-09-09'
Description: 'sputnik - Lambda - Version %%VERSION%%'

Parameters:
    sourceBucket:
        Type: String
        Description: S3 Bucket for Lambda code.
    lambdaSourceKeyPrefix:
        Type: String
        Description: S3 Bucket Key prefix for Lambda code.
    addonsSourceKeyPrefix:
        Type: String
        Description: S3 Bucket Key prefix for Addons code.
    destBucketArn:
        Type: String
        Description: ARN of the sputnik Website Bucket.
    dataBucket:
        Type: String
        Description: sputnik Data Bucket
    dataBucketArn:
        Type: String
        Description: ARN of the sputnik Data Bucket.
    settingsTable:
        Type: String
        Description: DynamoDB Table for storing the application settings
    devicesTable:
        Type: String
        Description: DynamoDB Table for storing the devices
    deviceTypesTable:
        Type: String
        Description: DynamoDB Table for storing the device types
    deviceBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the device blueprints
    deploymentsTable:
        Type: String
        Description: DynamoDB Table for storing the deployments
    solutionsTable:
        Type: String
        Description: DynamoDB Table for storing the solutions
    solutionBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the solution blueprints
    IAMRoleArnForGreengrassGroups:
        Type: String
        Description: sputnik Greengrass group role ARN
    IoTPolicyForGreengrassCores:
        Type: String
        Description: sputnik Greengrass IoT Policy
    userPoolId:
        Type: String
        Description: Cognito User Pool Id
    certsBucket:
        Type: String
        Description: sputnik Certs Bucket
    certsBucketArn:
        Type: String
        Description: sputnik Certs Bucket Arn
    cfnStackId:
        Type: String
        Description: sputnik CFN stack id, used by addons

Resources:

    # Nested stack - Custom resource - S3 Helper
    CFStackForCustomResourceS3Helper:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-helper-s3.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                destBucketArn: !Ref destBucketArn
                dataBucketArn: !Ref dataBucketArn

    # Nested stack - Custom resource - Thing Groups Helper
    CFStackForCustomResourceThingGroupsHelper:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-helper-thing-groups.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix

    # Nested stack - Custom resource - Utils Helper
    CFStackForCustomResourceUtilsHelper:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-helper-utils.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                destBucketArn: !Ref destBucketArn
                dataBucketArn: !Ref dataBucketArn
                settingsTable: !Ref settingsTable
                devicesTable: !Ref devicesTable
                deviceBlueprintsTable: !Ref deviceBlueprintsTable
                deviceTypesTable: !Ref deviceTypesTable
                solutionsTable: !Ref solutionsTable
                solutionBlueprintsTable: !Ref solutionBlueprintsTable

    # Nested stack - MicroService - Addons
    CFStackForAddonsService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-service-addons.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                addonsSourceKeyPrefix: !Ref addonsSourceKeyPrefix
                userPoolId: !Ref userPoolId
                cfnStackId: !Ref cfnStackId

    # Nested stack - MicroService - Admin
    CFStackForAdminService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-service-admin.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                userPoolId: !Ref userPoolId

    # Nested stack - MicroService - Deployments
    CFStackForDeploymentsService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-service-deployments.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                settingsTable: !Ref settingsTable
                devicesTable: !Ref devicesTable
                deviceTypesTable: !Ref deviceTypesTable
                deviceBlueprintsTable: !Ref deviceBlueprintsTable
                deploymentsTable: !Ref deploymentsTable
                dataBucket: !Ref dataBucket
                IAMRoleArnForGreengrassGroups: !Ref IAMRoleArnForGreengrassGroups
                IoTPolicyForGreengrassCores: !Ref IoTPolicyForGreengrassCores

    # Nested stack - MicroService - Devices
    CFStackForDevicesService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-service-devices.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                settingsTable: !Ref settingsTable
                devicesTable: !Ref devicesTable
                deviceTypesTable: !Ref deviceTypesTable
                certsBucket: !Ref certsBucket
                certsBucketArn: !Ref certsBucketArn

    # Nested stack - MicroService - Factory Reset
    CFStackForFactoryResetService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-service-factoryreset.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                settingsTable: !Ref settingsTable
                deviceTypesTable: !Ref deviceTypesTable
                deviceBlueprintsTable: !Ref deviceBlueprintsTable
                solutionBlueprintsTable: !Ref solutionBlueprintsTable

    # Nested stack - MicroService - Settings
    CFStackForSettingsService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-service-settings.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                iotThingAutoRegistrationTopicRuleName: !GetAtt CFStackForThingAutoRegistrationService.Outputs.iotThingAutoRegistrationTopicRuleName
                settingsTable: !Ref settingsTable

    # Nested stack - MicroService - Solutions
    CFStackForSolutionsService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-service-solutions.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                settingsTable: !Ref settingsTable
                devicesTable: !Ref devicesTable
                deviceTypesTable: !Ref deviceTypesTable
                deviceBlueprintsTable: !Ref deviceBlueprintsTable
                solutionBlueprintsTable: !Ref solutionBlueprintsTable
                solutionsTable: !Ref solutionsTable

    # Nested stack - MicroService - Thing Auto Registration
    CFStackForThingAutoRegistrationService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-service-thing-auto-registration.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                settingsTable: !Ref settingsTable
                devicesTable: !Ref devicesTable

    # Nested stack - MicroService - Admin
    CFStackForCertDeletorService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], 'sputnik/%%VERSION%%/cf/lambda/sputnik-lambda-service-cert-deletor.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Ref lambdaSourceKeyPrefix
                certsBucket: !Ref certsBucket


Outputs:
    customResourceS3HelperArn:
        Description: 'Custom Resource S3 Helper ARN'
        Value: !GetAtt CFStackForCustomResourceS3Helper.Outputs.customResourceS3HelperArn
    customResourceThingGroupsHelperArn:
        Description: 'Custom Resource Thing Groups Helper ARN'
        Value: !GetAtt CFStackForCustomResourceThingGroupsHelper.Outputs.customResourceThingGroupsHelperArn
    customResourceUtilsHelperArn:
        Description: 'Custom Resource Utils Helper ARN'
        Value: !GetAtt CFStackForCustomResourceUtilsHelper.Outputs.customResourceUtilsHelperArn
    lambdaServiceDeploymentsArn:
        Description: 'Deployments Service ARN'
        Value: !GetAtt CFStackForDeploymentsService.Outputs.lambdaServiceDeploymentsArn
    lambdaServiceAddonsArn:
        Description: 'Addons Service ARN'
        Value: !GetAtt CFStackForAddonsService.Outputs.lambdaServiceAddonsArn
    lambdaServiceAdminArn:
        Description: 'Admin Service ARN'
        Value: !GetAtt CFStackForAdminService.Outputs.lambdaServiceAdminArn
    lambdaServiceDevicesArn:
        Description: 'Devices Service ARN'
        Value: !GetAtt CFStackForDevicesService.Outputs.lambdaServiceDevicesArn
    lambdaServiceFactoryResetArn:
        Description: "Stats Service ARN"
        Value: !GetAtt CFStackForFactoryResetService.Outputs.lambdaServiceFactoryResetArn
    lambdaServiceSettingsArn:
        Description: "Settings Service ARN"
        Value: !GetAtt CFStackForSettingsService.Outputs.lambdaServiceSettingsArn
    lambdaServiceSolutionsArn:
        Description: 'Solutions Service ARN'
        Value: !GetAtt CFStackForSolutionsService.Outputs.lambdaServiceSolutionsArn
    lambdaServiceThingAutoRegistrationArn:
        Description: "Thing Auto Registration Service ARN"
        Value: !GetAtt CFStackForThingAutoRegistrationService.Outputs.lambdaServiceThingAutoRegistrationArn
    iotThingAutoRegistrationTopicRuleName:
        Description: "ThingAutoRegistration Topic Rule Name"
        Value: !GetAtt CFStackForThingAutoRegistrationService.Outputs.iotThingAutoRegistrationTopicRuleName
    lambdaServiceCertDeletorArn:
        Description: 'Cert Deletor Service ARN'
        Value: !GetAtt CFStackForCertDeletorService.Outputs.lambdaServiceCertDeletorArn

