AWSTemplateFormatVersion: '2010-09-09'
Description: 'sputnik - CF Custom Resource Helper UUID Lambda Macro - Version %%VERSION%%'

Resources:

    customResourceUUIDHelperRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: 'Allow'
                      Principal:
                          Service:
                              - 'lambda.amazonaws.com'
                      Action:
                          - 'sts:AssumeRole'
            Path: '/'

    customResourceUUIDPermissions:
        Type: 'AWS::Lambda::Permission'
        Properties:
            Action: 'lambda:InvokeFunction'
            FunctionName: !GetAtt customResourceUUIDHelper.Arn
            Principal: 'cloudformation.amazonaws.com'

    customResourceUUIDHelper:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'sputnik-custom-resource-helper-uuid-macro'
            Description: 'sputnik Custom resource helper for deploying the app'
            Code:
                ZipFile: |
                    const uuid = require('uuid');
                    exports.handler = async () => {
                        return uuid.v4();
                    };
            Handler: index.handler
            Runtime: nodejs8.10
            Role: !GetAtt customResourceUUIDHelperRole.Arn

    UUID:
        Type: AWS::CloudFormation::Transform
        Properties:
            Name: !Sub "${AWS::AccountId}::UUID"
            Description: "Generates a UUID string"
            RoutingTable:
                '*': 0_1
            Versions:
                -
                    VersionName: 0_1
                    Description: "Version 0_1 of the UUID Generator"
                    FunctionName: !GetAtt customResourceUUIDHelper.Arn
            ExecutionPolicy:
                Version: 2012-10-17
                Id: AllowOtherAccountPolicy
                Statement:
                    -
                        Sid: AllowExecution
                        Effect: Allow
                        Principal:
                            AWS: !Sub '${AWS::AccountId}'
                        Action: "cloudformation:CreateChangeSet"
                        Resource: !Sub "arn:*:cloudformation:${AWS::Region}:${AWS::AccountId}:transform/UUID"
