AWSTemplateFormatVersion: '2010-09-09'
Description: 'sputnik - Micro Service Lambda - Addons - Version %%VERSION%%'
Parameters:
    sourceBucket:
        Type: String
        Description: S3 Bucket for Lambda code.
    lambdaSourceKeyPrefix:
        Type: String
        Description: S3 Bucket Key prefix for Lambda code.
    addonsSourceKeyPrefix:
        Type: String
        Description: S3 Bucket Key prefix for Addons code.
    userPoolId:
        Type: String
        Description: Cognito User Pool Id
    cfnStackId:
        Type: String
        Description: sputnik CFN stack id, used by addons

Resources:

    lambdaServiceAddonsRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Principal:
                            Service:
                                - 'lambda.amazonaws.com'
                        Action:
                                - 'sts:AssumeRole'
            Path: '/'

    lambdaServiceAddonsPolicy:
        Type: 'AWS::IAM::ManagedPolicy'
        Properties:
            Description: 'sputnik policy for the Addons microservice Lambda function.'
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Action:
                            - 'logs:CreateLogGroup'
                            - 'logs:CreateLogStream'
                            - 'logs:PutLogEvents'
                        Resource: !Join ['', ['arn:aws:logs:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':log-group:/aws/lambda/', !Ref lambdaServiceAddons, ':*']]
                    -
                        Effect: 'Allow'
                        Action:
                            - 'cloudformation:CreateStack'
                            - 'cloudformation:UpdateStack'
                            - 'cloudformation:DescribeStacks'
                        Resource:
                            - '*'
            Roles:
                - !Ref 'lambdaServiceAddonsRole'

    lambdaServiceAddons:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'sputnik-addons-service'
            Description: 'sputnik Addons microservice'
            Code:
                S3Bucket: !Ref sourceBucket
                S3Key: !Join ['/', [!Ref lambdaSourceKeyPrefix, 'sputnik-addons-service.zip']]
            Handler: index.handler
            Runtime: nodejs8.10
            Role: !GetAtt lambdaServiceAddonsRole.Arn
            Timeout: 60
            MemorySize: 256
            Environment:
                Variables:
                    USER_POOL_ID: !Ref userPoolId
                    LOGGING_LEVEL: 2
                    CFN_STACK_ID: !Ref cfnStackId
                    SOURCE_BUCKET: !Ref sourceBucket
                    ADDONS_SOURCE_KEY_PREFIX: !Ref addonsSourceKeyPrefix


Outputs:
    lambdaServiceAddonsArn:
        Description: 'Addons Service ARN'
        Value: !GetAtt lambdaServiceAddons.Arn
