AWSTemplateFormatVersion: '2010-09-09'
Description: 'sputnik - Micro Service Lambda - Deployments - Version %%VERSION%%'
Parameters:
    sourceBucket:
        Type: String
        Description: S3 Bucket for Lambda code.
    lambdaSourceKeyPrefix:
        Type: String
        Description: S3 Bucket Key prefix for Lambda code.
    settingsTable:
        Type: String
        Description: DynamoDB Table for storing the application settings
    devicesTable:
        Type: String
        Description: DynamoDB Table for storing the devices
    deviceTypesTable:
        Type: String
        Description: DynamoDB Table for storing the device types
    deviceBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the device blueprints
    deploymentsTable:
        Type: String
        Description: DynamoDB Table for storing the deployments
    dataBucket:
        Type: String
        Description: sputnik Data Bucket
    IAMRoleArnForGreengrassGroups:
        Type: String
        Description: sputnik Greengrass Group Role ARN
    IoTPolicyForGreengrassCores:
        Type: String
        Description: sputnik Greengrass IoT Policy


Resources:

    lambdaServiceDeploymentsRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Principal:
                            Service:
                                - 'lambda.amazonaws.com'
                        Action:
                                - 'sts:AssumeRole'
            Path: '/'

    lambdaServiceDeploymentsPolicy:
        Type: 'AWS::IAM::ManagedPolicy'
        Properties:
            Description: 'sputnik policy for the deployments microservice Lambda function.'
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Action:
                            - 'logs:CreateLogGroup'
                            - 'logs:CreateLogStream'
                            - 'logs:PutLogEvents'
                        Resource: !Join ['', ['arn:aws:logs:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':log-group:/aws/lambda/', !Ref lambdaServiceDeployments, ':*']]
                    -
                        Effect: 'Allow'
                        Action:
                            - 'dynamodb:BatchGetItem'
                            - 'dynamodb:BatchWriteItem'
                            - 'dynamodb:DeleteItem'
                            - 'dynamodb:GetItem'
                            - 'dynamodb:PutItem'
                            - 'dynamodb:Query'
                            - 'dynamodb:Scan'
                            - 'dynamodb:UpdateItem'
                        Resource:
                            - !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/', !Ref settingsTable]]
                            - !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/', !Ref devicesTable]]
                            - !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/', !Ref deviceTypesTable]]
                            - !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/', !Ref deviceBlueprintsTable]]
                            - !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/', !Ref deploymentsTable]]
                    -
                        Effect: 'Allow'
                        Action:
                            - 'iam:PassRole'
                        Resource:
                            - !Ref IAMRoleArnForGreengrassGroups
                    -
                        Effect: 'Allow'
                        Action:
                            # TODO: Too permissive for now.
                            - 'iot:*'
                            - 'greengrass:*'
                        Resource:
                            - '*'
            Roles:
                - !Ref 'lambdaServiceDeploymentsRole'

    lambdaServiceDeployments:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'sputnik-deployments-service'
            Description: 'sputnik deployments microservice'
            Code:
                S3Bucket: !Ref sourceBucket
                S3Key: !Join ['/', [!Ref lambdaSourceKeyPrefix, 'sputnik-deployments-service.zip']]
            Handler: index.handler
            Runtime: nodejs8.10
            Role: !GetAtt lambdaServiceDeploymentsRole.Arn
            Timeout: 60
            MemorySize: 256
            Environment:
                Variables:
                    TABLE_DEVICES: !Ref devicesTable
                    TABLE_DEVICE_TYPES: !Ref deviceTypesTable
                    TABLE_DEVICE_BLUEPRINTS: !Ref deviceBlueprintsTable
                    TABLE_DEPLOYMENTS: !Ref deploymentsTable
                    TABLE_SETTINGS: !Ref settingsTable
                    AWS_ACCOUNT: !Ref 'AWS::AccountId'
                    IAM_ROLE_ARN_FOR_GREENGRASS_GROUPS: !Ref IAMRoleArnForGreengrassGroups
                    IOT_POLICY_GREENGRASS_CORE: !Ref IoTPolicyForGreengrassCores
                    DATA_BUCKET: !Ref dataBucket
                    LOGGING_LEVEL: 2


Outputs:
    lambdaServiceDeploymentsArn:
        Description: 'Deployments Service ARN'
        Value: !GetAtt lambdaServiceDeployments.Arn
