AWSTemplateFormatVersion: '2010-09-09'
Description: 'sputnik - Lambda - Version %%VERSION%%'

Parameters:
    sourceBucket:
        Type: String
        Description: S3 Bucket for Lambda code.
    sourceKeyPrefix:
        Type: String
        Description: S3 Bucket Key prefix for code.
    destBucketArn:
        Type: String
        Description: ARN of the sputnik Website Bucket.
    dataBucket:
        Type: String
        Description: sputnik Data Bucket
    dataBucketArn:
        Type: String
        Description: ARN of the sputnik Data Bucket.
    settingsTable:
        Type: String
        Description: DynamoDB Table for storing the application settings
    devicesTable:
        Type: String
        Description: DynamoDB Table for storing the devices
    deviceTypesTable:
        Type: String
        Description: DynamoDB Table for storing the device types
    deviceBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the device blueprints
    deploymentsTable:
        Type: String
        Description: DynamoDB Table for storing the deployments
    systemsTable:
        Type: String
        Description: DynamoDB Table for storing the systems
    systemBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the system blueprints
    greengrassServiceRoleArn:
        Type: String
        Description: IAM Role Arn for Greengrass Service
    iamRoleArnForGreengrassGroups:
        Type: String
        Description: sputnik Greengrass group role ARN
    iotPolicyForGreengrassCores:
        Type: String
        Description: sputnik Greengrass IoT Policy
    iotConnectPolicyForSputnikCertificates:
        Type: String
        Description: sputnik default connect IoT Policy for new certs
    userPoolId:
        Type: String
        Description: Cognito User Pool Id
    cfnStackId:
        Type: String
        Description: sputnik CFN stack id, used by addons

Resources:

    # Nested stack - Custom resource - S3 Helper
    CFStackForCustomResourceS3Helper:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Ref sourceKeyPrefix, 'cf/lambda/sputnik-lambda-helper-s3.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Join ['/', [!Ref sourceKeyPrefix, 'lambda']]
                destBucketArn: !Ref destBucketArn
                dataBucketArn: !Ref dataBucketArn

    # Nested stack - Custom resource - Utils Helper
    CFStackForCustomResourceUtilsHelper:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Ref sourceKeyPrefix, 'cf/lambda/sputnik-lambda-helper-utils.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Join ['/', [!Ref sourceKeyPrefix, 'lambda']]
                destBucketArn: !Ref destBucketArn
                dataBucketArn: !Ref dataBucketArn
                settingsTable: !Ref settingsTable
                devicesTable: !Ref devicesTable
                deviceBlueprintsTable: !Ref deviceBlueprintsTable
                deviceTypesTable: !Ref deviceTypesTable
                systemsTable: !Ref systemsTable
                systemBlueprintsTable: !Ref systemBlueprintsTable
                greengrassServiceRoleArn: !Ref greengrassServiceRoleArn

    # Nested stack - Custom resource - UUID Helper
    CFStackForCustomResourceUUIDHelper:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Ref sourceKeyPrefix, 'cf/lambda/sputnik-lambda-helper-uuid.yml']]

    # Nested stack - MicroService - Admin
    CFStackForAdminService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Ref sourceKeyPrefix, 'cf/lambda/sputnik-lambda-service-admin.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Join ['/', [!Ref sourceKeyPrefix, 'lambda']]
                userPoolId: !Ref userPoolId

    # Nested stack - MicroService - Deployments
    CFStackForDeploymentsService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Ref sourceKeyPrefix, 'cf/lambda/sputnik-lambda-service-deployments.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Join ['/', [!Ref sourceKeyPrefix, 'lambda']]
                settingsTable: !Ref settingsTable
                devicesTable: !Ref devicesTable
                deviceTypesTable: !Ref deviceTypesTable
                deviceBlueprintsTable: !Ref deviceBlueprintsTable
                deploymentsTable: !Ref deploymentsTable
                dataBucket: !Ref dataBucket
                iamRoleArnForGreengrassGroups: !Ref iamRoleArnForGreengrassGroups
                iotPolicyForGreengrassCores: !Ref iotPolicyForGreengrassCores

    # Nested stack - MicroService - Devices
    CFStackForDevicesService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Ref sourceKeyPrefix, 'cf/lambda/sputnik-lambda-service-devices.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Join ['/', [!Ref sourceKeyPrefix, 'lambda']]
                settingsTable: !Ref settingsTable
                devicesTable: !Ref devicesTable
                deviceTypesTable: !Ref deviceTypesTable
                iotConnectPolicyForSputnikCertificates: !Ref iotConnectPolicyForSputnikCertificates

    # Nested stack - MicroService - Settings
    CFStackForSettingsService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Ref sourceKeyPrefix, 'cf/lambda/sputnik-lambda-service-settings.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Join ['/', [!Ref sourceKeyPrefix, 'lambda']]
                iotJustInTimeOnBoardingTopicRuleName: !GetAtt CFStackForJustInTimeOnBoardingService.Outputs.iotJustInTimeOnBoardingTopicRuleName
                settingsTable: !Ref settingsTable

    # Nested stack - MicroService - Systems
    CFStackForSystemsService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Ref sourceKeyPrefix, 'cf/lambda/sputnik-lambda-service-systems.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Join ['/', [!Ref sourceKeyPrefix, 'lambda']]
                settingsTable: !Ref settingsTable
                devicesTable: !Ref devicesTable
                deviceTypesTable: !Ref deviceTypesTable
                deviceBlueprintsTable: !Ref deviceBlueprintsTable
                systemBlueprintsTable: !Ref systemBlueprintsTable
                systemsTable: !Ref systemsTable

    # Nested stack - MicroService - Just In Time On Boarding
    CFStackForJustInTimeOnBoardingService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Join ['-', ['%%BUCKET_NAME%%', Ref: 'AWS::Region']], !Ref sourceKeyPrefix, 'cf/lambda/sputnik-lambda-service-just-in-time-on-boarding.yml']]
            Parameters:
                sourceBucket: !Ref sourceBucket
                lambdaSourceKeyPrefix: !Join ['/', [!Ref sourceKeyPrefix, 'lambda']]
                settingsTable: !Ref settingsTable
                devicesTable: !Ref devicesTable


Outputs:
    customResourceS3HelperArn:
        Description: 'Custom Resource S3 Helper ARN'
        Value: !GetAtt CFStackForCustomResourceS3Helper.Outputs.customResourceS3HelperArn
    customResourceUtilsHelperArn:
        Description: 'Custom Resource Utils Helper ARN'
        Value: !GetAtt CFStackForCustomResourceUtilsHelper.Outputs.customResourceUtilsHelperArn
    lambdaServiceDeploymentsArn:
        Description: 'Deployments Service ARN'
        Value: !GetAtt CFStackForDeploymentsService.Outputs.lambdaServiceDeploymentsArn
    lambdaServiceAdminArn:
        Description: 'Admin Service ARN'
        Value: !GetAtt CFStackForAdminService.Outputs.lambdaServiceAdminArn
    lambdaServiceDevicesArn:
        Description: 'Devices Service ARN'
        Value: !GetAtt CFStackForDevicesService.Outputs.lambdaServiceDevicesArn
    lambdaServiceSettingsArn:
        Description: "Settings Service ARN"
        Value: !GetAtt CFStackForSettingsService.Outputs.lambdaServiceSettingsArn
    lambdaServiceSystemsArn:
        Description: 'Systems Service ARN'
        Value: !GetAtt CFStackForSystemsService.Outputs.lambdaServiceSystemsArn
    lambdaServiceJustInTimeOnBoardingArn:
        Description: "Just In Time On Boarding Service ARN"
        Value: !GetAtt CFStackForJustInTimeOnBoardingService.Outputs.lambdaServiceJustInTimeOnBoardingArn
    iotJustInTimeOnBoardingTopicRuleName:
        Description: "JustInTimeOnBoarding Topic Rule Name"
        Value: !GetAtt CFStackForJustInTimeOnBoardingService.Outputs.iotJustInTimeOnBoardingTopicRuleName
