# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: "2010-09-09"
Description: "sputnik - Micro Service Lambda - Just In Time OnBoarding - Version %%VERSION%%"
Parameters:
    sourceBucket:
        Type: String
        Description: S3 Bucket for Lambda code.
    lambdaSourceKeyPrefix:
        Type: String
        Description: S3 Bucket Key prefix for Lambda code.
    devicesTable:
        Type: String
        Description: DynamoDB Table for storing the application devices
    settingsTable:
        Type: String
        Description: DynamoDB Table for storing the application settings

Resources:

    lambdaServiceJustInTimeOnBoardingRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: "Allow"
                        Principal:
                            Service:
                                - "lambda.amazonaws.com"
                        Action:
                                - "sts:AssumeRole"
            Path: "/"

    lambdaServiceJustInTimeOnBoardingPolicy:
        Type: 'AWS::IAM::ManagedPolicy'
        Properties:
            Description: 'sputnik policy for the Just In Time On Boarding microservice Lambda function.'
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Action:
                            - "logs:CreateLogGroup"
                            - "logs:CreateLogStream"
                            - "logs:PutLogEvents"
                        Resource: !Join ["", ["arn:aws:logs:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":log-group:/aws/lambda/", !Ref lambdaServiceJustInTimeOnBoarding, ":*"]]
                    -
                        Effect: "Allow"
                        Action:
                            - "dynamodb:BatchGetItem"
                            - "dynamodb:BatchWriteItem"
                            - "dynamodb:DeleteItem"
                            - "dynamodb:GetItem"
                            - "dynamodb:PutItem"
                            - "dynamodb:Query"
                            - "dynamodb:Scan"
                            - "dynamodb:UpdateItem"
                        Resource:
                            - !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/', !Ref devicesTable]]
                            - !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/', !Ref settingsTable]]
                    -
                        Effect: "Allow"
                        Action:
                            # TODO: Too permissive for now.
                            - "iot:*"
                            - "greengrass:*"
                        Resource:
                            - "*"
            Roles:
                - !Ref 'lambdaServiceJustInTimeOnBoardingRole'

    lambdaServiceJustInTimeOnBoarding:
        Type: "AWS::Lambda::Function"
        Properties:
            FunctionName: "sputnik-just-in-time-on-boarding-service"
            Description: "sputnik just in time on boarding microservice"
            Code:
                S3Bucket: !Ref sourceBucket
                S3Key: !Join ["/", [!Ref lambdaSourceKeyPrefix, "sputnik-just-in-time-on-boarding-service.zip"]]
            Handler: index.handler
            Runtime: nodejs8.10
            Role: !GetAtt lambdaServiceJustInTimeOnBoardingRole.Arn
            Timeout: 60
            MemorySize: 256
            Environment:
                Variables:
                    TABLE_DEVICES: !Ref devicesTable
                    TABLE_SETTINGS: !Ref settingsTable
                    LOGGING_LEVEL: 2

    iotJustInTimeOnBoardingTopicRule:
        Type: "AWS::IoT::TopicRule"
        Properties:
            TopicRulePayload:
                RuleDisabled: false
                Sql: >-
                    SELECT topic() as topic, * from '$aws/events/presence/#'
                Actions:
                    - Lambda:
                        FunctionArn: !GetAtt lambdaServiceJustInTimeOnBoarding.Arn

    iotJustInTimeOnBoardingLambdaInvocationPermission:
        Type: AWS::Lambda::Permission
        Properties:
            SourceArn: !Join [ "", [ "arn:aws:iot:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":rule/", !Ref "iotJustInTimeOnBoardingTopicRule" ] ]
            Action: lambda:InvokeFunction
            Principal: iot.amazonaws.com
            FunctionName: !GetAtt lambdaServiceJustInTimeOnBoarding.Arn
            SourceAccount: !Ref AWS::AccountId


Outputs:
    lambdaServiceJustInTimeOnBoardingArn:
        Description: "Just in time on boarding Service ARN"
        Value: !GetAtt lambdaServiceJustInTimeOnBoarding.Arn
    iotJustInTimeOnBoardingTopicRuleName:
        Description: "JustInTimeOnBoarding Topic Rule Name"
        Value: !Ref iotJustInTimeOnBoardingTopicRule
