# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: '2010-09-09'
Description: 'sputnik - Micro Service Lambda - Devices - Version %%VERSION%%'
Parameters:
    sourceBucket:
        Type: String
        Description: S3 Bucket for Lambda code.
    lambdaSourceKeyPrefix:
        Type: String
        Description: S3 Bucket Key prefix for Lambda code.
    settingsTable:
        Type: String
        Description: DynamoDB Table for storing the application settings
    devicesTable:
        Type: String
        Description: DynamoDB Table for storing the devices
    deviceTypesTable:
        Type: String
        Description: DynamoDB Table for storing the device types
    iotConnectPolicyForSputnikCertificates:
        Type: String
        Description: sputnik default connect IoT Policy for new certs

Resources:

    lambdaServiceDevicesRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Principal:
                            Service:
                                - 'lambda.amazonaws.com'
                        Action:
                                - 'sts:AssumeRole'
            Path: '/'

    lambdaServiceDevicesPolicy:
        Type: 'AWS::IAM::ManagedPolicy'
        Properties:
            Description: 'sputnik policy for the devices microservice Lambda function.'
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Action:
                            - 'logs:CreateLogGroup'
                            - 'logs:CreateLogStream'
                            - 'logs:PutLogEvents'
                        Resource: !Join ['', ['arn:aws:logs:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':log-group:/aws/lambda/', !Ref lambdaServiceDevices, ':*']]
                    -
                        Effect: 'Allow'
                        Action:
                            - 'dynamodb:BatchGetItem'
                            - 'dynamodb:BatchWriteItem'
                            - 'dynamodb:DeleteItem'
                            - 'dynamodb:GetItem'
                            - 'dynamodb:PutItem'
                            - 'dynamodb:Query'
                            - 'dynamodb:Scan'
                            - 'dynamodb:UpdateItem'
                        Resource:
                            - !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/', !Ref settingsTable]]
                            - !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/', !Ref devicesTable]]
                            - !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/', !Ref deviceTypesTable]]
                    -
                        Effect: 'Allow'
                        Action:
                            # Too permissive for now.
                            # iot:createCertificateFromCsr
                            - 'iot:*'
                            - 'greengrass:*'
                        Resource:
                            - '*'
            Roles:
                - !Ref 'lambdaServiceDevicesRole'

    lambdaServiceDevices:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'sputnik-devices-service'
            Description: 'sputnik devices microservice'
            Code:
                S3Bucket: !Ref sourceBucket
                S3Key: !Join ['/', [!Ref lambdaSourceKeyPrefix, 'sputnik-devices-service.zip']]
            Handler: index.handler
            Runtime: nodejs8.10
            Role: !GetAtt lambdaServiceDevicesRole.Arn
            Timeout: 60
            MemorySize: 256
            Environment:
                Variables:
                    TABLE_DEVICES: !Ref devicesTable
                    TABLE_DEVICE_TYPES: !Ref deviceTypesTable
                    TABLE_SETTINGS: !Ref settingsTable
                    IOT_DEFAULT_CONNECT_POLICY: !Ref iotConnectPolicyForSputnikCertificates
                    LOGGING_LEVEL: 2


Outputs:
    lambdaServiceDevicesArn:
        Description: 'Devices Service ARN'
        Value: !GetAtt lambdaServiceDevices.Arn
