AWSTemplateFormatVersion: '2010-09-09'
Description: 'My Things Management - DynamoDB Table - Device Blueprints - Version %%VERSION%%'

Resources:

    deviceBlueprintsTable:
        Type: "AWS::DynamoDB::Table"
        DeletionPolicy: "Delete"
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: "id"
                    AttributeType: "S"
            KeySchema:
                -
                    AttributeName: "id"
                    KeyType: "HASH"
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
            SSESpecification:
                SSEEnabled: true
            TableName: "mythings-mgmt-device-blueprints"

    deviceBlueprintsDynamoDBScalingRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: "Allow"
                        Principal:
                            Service:
                                - application-autoscaling.amazonaws.com
                        Action:
                            - "sts:AssumeRole"
            Path: "/"
            Policies:
                -
                    PolicyName: "root"
                    PolicyDocument:
                        Version: "2012-10-17"
                        Statement:
                            -
                                Effect: "Allow"
                                Action:
                                    - "cloudwatch:PutMetricAlarm"
                                    - "cloudwatch:DescribeAlarms"
                                    - "cloudwatch:GetMetricStatistics"
                                    - "cloudwatch:SetAlarmState"
                                    - "cloudwatch:DeleteAlarms"
                                Resource: "*"
                            -
                                Effect: "Allow"
                                Action:
                                    - "dynamodb:DescribeTable"
                                    - "dynamodb:UpdateTable"
                                    - "dynamodb:DescribeGlobalTable"
                                    - "dynamodb:UpdateGlobalTable"
                                Resource:
                                    - !GetAtt deviceBlueprintsTable.Arn

    deviceBlueprintsReadCapacityScalableTarget:
        Type: "AWS::ApplicationAutoScaling::ScalableTarget"
        Properties:
            MaxCapacity: 100
            MinCapacity: 5
            ResourceId: !Join ["/", ["table",  !Ref "deviceBlueprintsTable"]]
            RoleARN: !GetAtt deviceBlueprintsDynamoDBScalingRole.Arn
            ScalableDimension: dynamodb:table:ReadCapacityUnits
            ServiceNamespace: dynamodb

    deviceBlueprintsReadScalingPolicy:
        Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
        Properties:
            PolicyName: deviceBlueprintsReadScalingPolicy
            PolicyType: TargetTrackingScaling
            ScalingTargetId: !Ref deviceBlueprintsReadCapacityScalableTarget
            TargetTrackingScalingPolicyConfiguration:
                TargetValue: 70.0
                ScaleInCooldown: 60
                ScaleOutCooldown: 60
                PredefinedMetricSpecification:
                    PredefinedMetricType: DynamoDBReadCapacityUtilization

Outputs:
    deviceBlueprintsTable:
        Description: "DynamoDB Device Blueprints Table"
        Value: !Ref deviceBlueprintsTable
