AWSTemplateFormatVersion: '2010-09-09'
Description: 'sputnik - DynamoDB Table - Data Store - Version %%VERSION%%'

Resources:

    dataStoreTable:
        Type: "AWS::DynamoDB::Table"
        DeletionPolicy: "Delete"
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: "ThingNameAndMetric"
                    AttributeType: "S"
                -
                    AttributeName: "Timestamp"
                    AttributeType: "N"
            KeySchema:
                -
                    AttributeName: "ThingNameAndMetric"
                    KeyType: "HASH"
                -
                    AttributeName: "Timestamp"
                    KeyType: "RANGE"
            ProvisionedThroughput:
                ReadCapacityUnits: 20
                WriteCapacityUnits: 20
            SSESpecification:
                SSEEnabled: true
            TimeToLiveSpecification:
                AttributeName: 'ExpirationTime'
                Enabled: Yes
            TableName: "sputnik-data-store"

Outputs:
    dataStoreTable:
        Description: "DynamoDB Data Store Table"
        Value: !Ref dataStoreTable
