AWSTemplateFormatVersion: '2010-09-09'
Description: 'sputnik - DynamoDB Table - Solution Blueprints - Version %%VERSION%%'

Resources:

    solutionBlueprintsTable:
        Type: "AWS::DynamoDB::Table"
        DeletionPolicy: "Delete"
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: "id"
                    AttributeType: "S"
            KeySchema:
                -
                    AttributeName: "id"
                    KeyType: "HASH"
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
            SSESpecification:
                SSEEnabled: true
            TableName: "sputnik-solution-blueprints"

Outputs:
    solutionBlueprintsTable:
        Description: "DynamoDB Solution Blueprints Table"
        Value: !Ref solutionBlueprintsTable
