# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: '2010-09-09'
Description: 'sputnik - DynamoDB Table - Systems - Version %%VERSION%%'

Resources:

    systemsTable:
        Type: "AWS::DynamoDB::Table"
        DeletionPolicy: "Delete"
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: "id"
                    AttributeType: "S"
            KeySchema:
                -
                    AttributeName: "id"
                    KeyType: "HASH"
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
            SSESpecification:
                SSEEnabled: true
            TableName: "sputnik-systems"


Outputs:
    systemsTable:
        Description: "DynamoDB Systems Table"
        Value: !Ref systemsTable
