# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: '2010-09-09'
Description: 'sputnik - DynamoDB Table - Deployments - Version %%VERSION%%'

Resources:
    deploymentsTable:
        Type: "AWS::DynamoDB::Table"
        DeletionPolicy: "Delete"
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: "thingId"
                    AttributeType: "S"
                -
                    AttributeName: "deploymentId"
                    AttributeType: "S"
            KeySchema:
                -
                    AttributeName: "thingId"
                    KeyType: "HASH"
                -
                    AttributeName: "deploymentId"
                    KeyType: "RANGE"
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
            SSESpecification:
                SSEEnabled: true
            TableName: "sputnik-deployments"

Outputs:
    deploymentsTable:
        Description: "DynamoDB Deployments Table"
        Value: !Ref deploymentsTable
