AWSTemplateFormatVersion: '2010-09-09'
Description: 'Murata Vibration Sensor Network - Sputnik setup v1.0'
Parameters:
    addonSourceBucket:
        Type: String
        Description: sputnik S3 bucket.
    addonSourceKeyPrefix:
        Type: String
        Description: sputnik Source key prefix.
    deviceBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the device blueprints
    deviceTypesTable:
        Type: String
        Description: DynamoDB Table for storing the device types
    solutionBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the solution blueprints
    customResourceUtilsHelperArn:
        Type: String
        Description: Utils custom resource helper ARN
    iamRoleForGreengrassGroups:
        Type: String
        Description: Greengrass Group Role
    uuid:
        Type: String
        Description: UUID of the deployment

Resources:

    MurataGreengrassGroupPolicy:
        Type: 'AWS::IAM::ManagedPolicy'
        Properties:
            Description: 'Policy for the sputnik Greengrass Role.'
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Action:
                            - 'logs:CreateLogStream'
                            - 'logs:DescribeLogStreams'
                            - 'logs:PutLogEvents'
                            - 'logs:CreateLogGroup'
                        Resource: 'arn:aws:logs:*:*:log-group:/aws/greengrass/*'
            Roles:
                -
                    !Ref iamRoleForGreengrassGroups

    MurataDeviceTypes:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref addonSourceBucket
            sourceS3Key: !Join ['/', [!Ref addonSourceKeyPrefix, 'murata', 'device-types']]
            table: !Ref deviceTypesTable
            customAction: 'dynamodbPutObjectsFromS3Folder'
            uuid: !Ref uuid

    MurataDeviceBlueprints:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref addonSourceBucket
            sourceS3Key: !Join ['/', [!Ref addonSourceKeyPrefix, 'murata', 'device-blueprints']]
            table: !Ref deviceBlueprintsTable
            customAction: 'dynamodbPutObjectsFromS3Folder'
            uuid: !Ref uuid

    MurataLambdaRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: 'Allow'
                      Principal:
                          Service:
                              - 'lambda.amazonaws.com'
                      Action:
                          - 'sts:AssumeRole'
            Path: '/'

    MurataVibrationSensorGatewayMainLambda:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'murata-vibration-sensor-gateway-main-lambda-python'
            Description: 'Murata Vibration Sensor Gateway Main Lambda Code'
            Code:
                S3Bucket: !Ref addonSourceBucket
                S3Key: !Join ['/', [!Ref addonSourceKeyPrefix, 'murata', 'lambdas', 'murata-vibration-sensor-gateway-main-lambda-python.zip']]
            Handler: lambda_function.lambda_handler
            Runtime: python2.7
            Role: !GetAtt MurataLambdaRole.Arn
            Timeout: 3
            MemorySize: 128
    MurataVibrationSensorGatewayMainLambdaVersion:
        Type: 'AWS::Lambda::Version'
        Properties:
            FunctionName:
                Ref: 'MurataVibrationSensorGatewayMainLambda'
            Description: 'A first version of murata-vibration-sensor-gateway-main-lambda-python'
    MurataVibrationSensorGatewayMainLambdaAlias:
        Type: 'AWS::Lambda::Alias'
        Properties:
            FunctionName: !Ref MurataVibrationSensorGatewayMainLambda
            FunctionVersion: !GetAtt MurataVibrationSensorGatewayMainLambdaVersion.Version
            Name: 'Prod'
