AWSTemplateFormatVersion: '2010-09-09'
Description: 'Murata Vibration Sensor Network - Sputnik setup v1.0'
Parameters:
    sourceS3Bucket:
        Type: String
        Description: sputnik S3 bucket.
    sourceKeyPrefix:
        Type: String
        Description: sputnik Source key prefix.
    deviceBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the device blueprints
    deviceTypesTable:
        Type: String
        Description: DynamoDB Table for storing the device types
    solutionBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the solution blueprints
    customResourceUtilsHelperArn:
        Type: String
        Description: Utils custom resource helper ARN
    deploymentUUID:
        Type: String
        Description: Used to force update / create of inits
    dataS3Bucket:
        Type: String
        Description: sputnik Data S3 Bucket
    dataS3BucketArn:
        Type: String
        Description: sputnik Data S3 Bucket ARN
    IAMRoleForGreengrassGroups:
        Type: String
        Description: Greengrass Group Role

Resources:

    MurataGreengrassGroupPolicy:
        Type: 'AWS::IAM::ManagedPolicy'
        Properties:
            Description: 'Policy for the sputnik Greengrass Role.'
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Action:
                            - 'logs:CreateLogStream'
                            - 'logs:DescribeLogStreams'
                            - 'logs:PutLogEvents'
                            - 'logs:CreateLogGroup'
                        Resource: 'arn:aws:logs:*:*:log-group:/aws/greengrass/*'
                    # -
                    #     Effect: 'Allow'
                    #     Action:
                    #         - 's3:ListBucket'
                    #         - 's3:GetObject'
                    #         - 's3:ListObjects'
                    #         - 's3:PutObject'
                    #     Resource:
                    #         - !Join ['/', [!Join ['', [!Ref dataS3BucketArn, '*']], '*']]
                    #         - !Join ['', [!Ref dataS3BucketArn, '*']]
            Roles:
                -
                    !Ref IAMRoleForGreengrassGroups

    MurataDeviceTypes:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref sourceS3Bucket
            sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'device-types']]
            uuid: !Ref deploymentUUID
            table: !Ref deviceTypesTable
            customAction: 'dynamodbPutObjectsFromS3Folder'

    # DefaultSDeviceBlueprints:
    #     Type: 'Custom::LoadLambda'
    #     Properties:
    #         ServiceToken: !Ref customResourceUtilsHelperArn
    #         Region: !Ref 'AWS::Region'
    #         sourceS3Bucket: !Ref sourceS3Bucket
    #         sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'device-blueprints']]
    #         uuid: !Ref deploymentUUID
    #         table: !Ref deviceBlueprintsTable
    #         customAction: 'dynamodbPutObjectsFromS3Folder'

    # DefaultSDeviceTypes:
    #     Type: 'Custom::LoadLambda'
    #     Properties:
    #         ServiceToken: !Ref customResourceUtilsHelperArn
    #         Region: !Ref 'AWS::Region'
    #         sourceS3Bucket: !Ref sourceS3Bucket
    #         sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'device-types']]
    #         uuid: !Ref deploymentUUID
    #         table: !Ref deviceTypesTable
    #         customAction: 'dynamodbPutObjectsFromS3Folder'

    # DefaultLambdaRole:
    #     Type: 'AWS::IAM::Role'
    #     Properties:
    #         AssumeRolePolicyDocument:
    #             Version: '2012-10-17'
    #             Statement:
    #                 - Effect: 'Allow'
    #                   Principal:
    #                       Service:
    #                           - 'lambda.amazonaws.com'
    #                   Action:
    #                       - 'sts:AssumeRole'
    #         Path: '/'
