AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Mini Connected Factory Demo v1.0'
Parameters:
    sourceS3Bucket:
        Type: String
        Description: sputnik S3 bucket.
    sourceKeyPrefix:
        Type: String
        Description: sputnik Source key prefix.
    greengrassSourceKeyPrefix:
        Type: String
        Description: sputnik source key prefix for the greengrass lambda function code
    deviceBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the device blueprints
    deviceTypesTable:
        Type: String
        Description: DynamoDB Table for storing the device types
    solutionBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the solution blueprints
    customResourceUtilsHelperArn:
        Type: String
        Description: Utils custom resource helper ARN
    deploymentUUID:
        Type: String
        Description: Used to force update / create of inits
    dataS3Bucket:
        Type: String
        Description: sputnik Data S3 Bucket
    dataS3BucketArn:
        Type: String
        Description: sputnik Data S3 Bucket ARN
    IAMRoleForGreengrassGroups:
        Type: String
        Description: Greengrass Group Role

Resources:
    MCFDeviceBlueprints:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref sourceS3Bucket
            sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'device-blueprints']]
            uuid: !Ref deploymentUUID
            table: !Ref deviceBlueprintsTable
            customAction: 'dynamodbPutObjectsFromS3Folder'

    MCFSolutionBlueprints:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref sourceS3Bucket
            sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'solution-blueprints']]
            uuid: !Ref deploymentUUID
            table: !Ref solutionBlueprintsTable
            customAction: 'dynamodbPutObjectsFromS3Folder'

    MCFLambdaRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: 'Allow'
                      Principal:
                          Service:
                              - 'lambda.amazonaws.com'
                      Action:
                          - 'sts:AssumeRole'
            Path: '/'

    MCFBeltSerialLambda:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'reinvent-2018-mcf-belt-serial-python'
            Description: 'sputnik AWS Mini Connected Factory Belt Lambda Code'
            Code:
                S3Bucket: !Ref sourceS3Bucket
                S3Key: !Join ['/', [!Ref greengrassSourceKeyPrefix, 'reinvent-2018-mcf-belt-serial-python.zip']]
            Handler: lambda_function.lambda_handler
            Runtime: python2.7
            Role: !GetAtt MCFLambdaRole.Arn
            Timeout: 3
            MemorySize: 128
    MCFBeltSerialLambdaVersion:
        Type: 'AWS::Lambda::Version'
        Properties:
            FunctionName:
                Ref: 'MCFBeltSerialLambda'
            Description: 'A first version of reinvent-2018-mcf-belt-serial-python'
    MCFBeltSerialLambdaAlias:
        Type: 'AWS::Lambda::Alias'
        Properties:
            FunctionName: !Ref MCFBeltSerialLambda
            FunctionVersion: !GetAtt MCFBeltSerialLambdaVersion.Version
            Name: 'MTM'


    MCFReInvent2018Lambda:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'reinvent-2018-mcf-python'
            Description: 'sputnik AWS reInvent 2018 Mini Connected Factory Lambda Code'
            Code:
                S3Bucket: !Ref sourceS3Bucket
                S3Key: !Join ['/', [!Ref greengrassSourceKeyPrefix, 'reinvent-2018-mcf-python.zip']]
            Handler: lambda_function.lambda_handler
            Runtime: python2.7
            Role: !GetAtt MCFLambdaRole.Arn
            Timeout: 3
            MemorySize: 128
    MCFReInvent2018LambdaVersion:
        Type: 'AWS::Lambda::Version'
        Properties:
            FunctionName:
                Ref: 'MCFReInvent2018Lambda'
            Description: 'A first version of reinvent-2018-mcf-python'
    MCFReInvent2018LambdaAlias:
        Type: 'AWS::Lambda::Alias'
        Properties:
            FunctionName: !Ref MCFReInvent2018Lambda
            FunctionVersion: !GetAtt MCFReInvent2018LambdaVersion.Version
            Name: 'MTM'

    MCFEBC2018Lambda:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'ebc-mcf-2018-python'
            Description: 'sputnik AWS EBC Mini Connected Factory Lambda Code'
            Code:
                S3Bucket: !Ref sourceS3Bucket
                S3Key: !Join ['/', [!Ref greengrassSourceKeyPrefix, 'ebc-mcf-2018-python.zip']]
            Handler: lambda_function.lambda_handler
            Runtime: python2.7
            Role: !GetAtt MCFLambdaRole.Arn
            Timeout: 3
            MemorySize: 128
    MCFEBC2018LambdaVersion:
        Type: 'AWS::Lambda::Version'
        Properties:
            FunctionName:
                Ref: 'MCFEBC2018Lambda'
            Description: 'A first version of ebc-mcf-2018-python'
    MCFEBC2018LambdaAlias:
        Type: 'AWS::Lambda::Alias'
        Properties:
            FunctionName: !Ref MCFEBC2018Lambda
            FunctionVersion: !GetAtt MCFEBC2018LambdaVersion.Version
            Name: 'MTM'

    MCFGreengrassGroupPolicy:
        Type: 'AWS::IAM::ManagedPolicy'
        Properties:
            Description: 'Policy for the sputnik Greengrass Role.'
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Action:
                            - 's3:ListBucket'
                            - 's3:GetObject'
                            - 's3:ListObjects'
                            - 's3:PutObject'
                        Resource:
                            - !Join ['/', [!Join ['', [!Ref dataS3BucketArn, '*']], '*']]
                            - !Join ['', [!Ref dataS3BucketArn, '*']]
            Roles:
                -
                    !Ref IAMRoleForGreengrassGroups


    MCFLegoModel:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref sourceS3Bucket
            destS3Bucket: !Ref dataS3Bucket
            sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'models', 'legomodel-v1.1.8-224-3cat.tar.gz']]
            destS3Key: !Join ['/', ['reinvent-2018-mcf', 'models', 'legomodel-v1.1.8-224-3cat.tar.gz']]
            uuid: !Ref deploymentUUID
            customAction: 'copyFileFromS3ToS3'

    MCFBoxesModel:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref sourceS3Bucket
            destS3Bucket: !Ref dataS3Bucket
            sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'models', 'boxes-v1.0.0-224-3cat.tar.gz']]
            destS3Key: !Join ['/', ['reinvent-2018-mcf', 'models', 'boxes-v1.0.0-224-3cat.tar.gz']]
            uuid: !Ref deploymentUUID
            customAction: 'copyFileFromS3ToS3'
