AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS re:Invent 2018 Mini Connected Factory Demo v1.0'
Parameters:
    sourceS3Bucket:
        Type: String
        Description: sputnik S3 bucket.
    sourceKeyPrefix:
        Type: String
        Description: sputnik Source key prefix.
    greengrassSourceKeyPrefix:
        Type: String
        Description: sputnik source key prefix for the greengrass lambda function code
    deviceBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the device blueprints
    deviceTypesTable:
        Type: String
        Description: DynamoDB Table for storing the device types
    solutionBlueprintsTable:
        Type: String
        Description: DynamoDB Table for storing the solution blueprints
    customResourceUtilsHelperArn:
        Type: String
        Description: Utils custom resource helper ARN
    deploymentUUID:
        Type: String
        Description: Used to force update / create of inits
    dataS3Bucket:
        Type: String
        Description: sputnik Data S3 Bucket
    dataS3BucketArn:
        Type: String
        Description: sputnik Data S3 Bucket ARN
    solutionsGreengrassGroupRole:
        Type: String
        Description: Greengrass Group Role

Resources:
    AMCF1DeviceBlueprints:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref sourceS3Bucket
            sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'device-blueprints']]
            uuid: !Ref deploymentUUID
            table: !Ref deviceBlueprintsTable
            customAction: 'dynamodbPutObjectsFromS3Folder'

    AMCF1SolutionBlueprints:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref sourceS3Bucket
            sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'solution-blueprints']]
            uuid: !Ref deploymentUUID
            table: !Ref solutionBlueprintsTable
            customAction: 'dynamodbPutObjectsFromS3Folder'

    AMCF1LambdaRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: 'Allow'
                      Principal:
                          Service:
                              - 'lambda.amazonaws.com'
                      Action:
                          - 'sts:AssumeRole'
            Path: '/'

    AMCF1BeltLambda:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'reinvent-2018-mcf-belt-serial-python'
            Description: 'sputnik AWS Mini Connected Factory Belt Lambda Code'
            Code:
                S3Bucket: !Ref sourceS3Bucket
                S3Key: !Join ['/', [!Ref greengrassSourceKeyPrefix, 'reinvent-2018-mcf-belt-serial-python.zip']]
            Handler: lambda_function.lambda_handler
            Runtime: python2.7
            Role: !GetAtt AMCF1LambdaRole.Arn
            Timeout: 3
            MemorySize: 128
    AMCF1BeltLambdaVersion:
        Type: 'AWS::Lambda::Version'
        Properties:
            FunctionName:
                Ref: 'AMCF1BeltLambda'
            Description: 'A first version of reinvent-2018-mcf-belt-serial-python'
    AMCF1BeltLambdaAlias:
        Type: 'AWS::Lambda::Alias'
        Properties:
            FunctionName: !Ref AMCF1BeltLambda
            FunctionVersion: !GetAtt AMCF1BeltLambdaVersion.Version
            Name: 'MTM'


    AMCF1FactoryPythonLambda:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: 'reinvent-2018-mcf-python'
            Description: 'sputnik AWS Mini Connected Factory Lambda Code'
            Code:
                S3Bucket: !Ref sourceS3Bucket
                S3Key: !Join ['/', [!Ref greengrassSourceKeyPrefix, 'reinvent-2018-mcf-python.zip']]
            Handler: lambda_function.lambda_handler
            Runtime: python2.7
            Role: !GetAtt AMCF1LambdaRole.Arn
            Timeout: 3
            MemorySize: 128
    AMCF1FactoryPythonLambdaVersion:
        Type: 'AWS::Lambda::Version'
        Properties:
            FunctionName:
                Ref: 'AMCF1FactoryPythonLambda'
            Description: 'A first version of reinvent-2018-mcf-python'
    AMCF1FactoryPythonLambdaAlias:
        Type: 'AWS::Lambda::Alias'
        Properties:
            FunctionName: !Ref AMCF1FactoryPythonLambda
            FunctionVersion: !GetAtt AMCF1FactoryPythonLambdaVersion.Version
            Name: 'MTM'



    AMCF1GreengrassGroupPolicy:
        Type: 'AWS::IAM::ManagedPolicy'
        Properties:
            Description: 'Policy for the sputnik Greengrass Role.'
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Action:
                            - 's3:ListBucket'
                            - 's3:GetObject'
                            - 's3:ListObjects'
                            - 's3:PutObject'
                        Resource:
                            - !Join ['/', [!Join ['', [!Ref dataS3BucketArn, '*']], '*']]
                            - !Join ['', [!Ref dataS3BucketArn, '*']]
            Roles:
                -
                    !Ref solutionsGreengrassGroupRole


    AMCF1LegoModel:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref sourceS3Bucket
            destS3Bucket: !Ref dataS3Bucket
            sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'models', 'legomodel-v1.1.8-224-3cat.tar.gz']]
            destS3Key: !Join ['/', ['reinvent-2018-mcf', 'models', 'legomodel-v1.1.8-224-3cat.tar.gz']]
            uuid: !Ref deploymentUUID
            customAction: 'copyFileFromS3ToS3'

    AMCF1BoxesModel:
        Type: 'Custom::LoadLambda'
        Properties:
            ServiceToken: !Ref customResourceUtilsHelperArn
            Region: !Ref 'AWS::Region'
            sourceS3Bucket: !Ref sourceS3Bucket
            destS3Bucket: !Ref dataS3Bucket
            sourceS3Key: !Join ['/', [!Ref sourceKeyPrefix, 'models', 'boxes-v1.0.0-224-3cat.tar.gz']]
            destS3Key: !Join ['/', ['reinvent-2018-mcf', 'models', 'boxes-v1.0.0-224-3cat.tar.gz']]
            uuid: !Ref deploymentUUID
            customAction: 'copyFileFromS3ToS3'
